### ISSUE TITLE
Automatiser le déployment de la doc ?

### ISSUE THREAD

**Issue by nborie** [PremierLangage/documentationpl#1]
A quel point serait-il possible, avec les technos actuellement choisies, d'avoir un déploiement continue et instantané de la documentation....

Après, il se peut que je ne procède pas correctement mais il me semble qu'un commit github sur le repo de la doc n'affecte pas en direct le rendu : https://documentationpl.readthedocs.io/fr/latest/

**Comment by nborie** [comment]
Je ne connaissais pas ReadTheDocs et j'imagine maintenant qu'une personne (plgitlogin il me semble) peut demander la recompilation de la doc à partir du repo Github...

Pour le long terme et la flexibilité, ce coté droits pour la recompilation + recompilation asynchrone des modifications présentes sur le repo github n'est pas extra. Si on ne peut pas avoir mieux tantpis mais par rapport à n'importe quel wiki (que tout le monde peut éditer et voir les modifs en instantannées...), je trouve la solution moyenne.

Typiquement là tout de suite, j'avais des trucs en tête à coucher par écrit mais que je n'ai pas moyen de voir les effets des 2 commits que j'ai envoyer il y a 2 heures... Je ne compte pas en rajouter sachant  qu'il y a une chance que je travaille pas correctement.

Une documentation soit en déploiement instantanée, soit avec un bouton publique de recompilation, c'est quand même cool... ReadTheDoc reste un truc rigolo mais je le trouve fort statique.

**Comment by qcoumes** [comment]
Normalement readsthedocs est recompiler à chaque push sur master.

**Comment by qcoumes** [comment]
Sûrement un réglage à faire

**Comment by plgitlogin** [comment]
C'est tout bon, ca compile à chaque push
